spring:
  application:
    name: atomikos-test
  datasource:
    platform: db2
  jpa:
    properties:
      hibernate:
#        default_schema: GESTION_COMISION
        hbm2ddl:
          auto: none
        dialect: org.hibernate.dialect.DB2Dialect
        connection:
          autocommit: false
datasource:
    ds1:
      max-pool-size: 5
      min-pool-size: 5
      xa-data-source-class-name: com.ibm.db2.jcc.DB2XADataSource
      use-driver-based-connection-validation: true
      init-connection-sql: set schema GESTION_COMISION
      xa-properties:
        serverName: axdesdb22.central.inditex.grp
        portNumber: 50000
        databaseName: INDITEX
        currentSchema: GESTION_COMISION
        user: uincome
        password: pzuUKBm1ppMGzzOn
        clientProgramName: ${metadata.jirakey}-${metadata.slot}
        driverType: 4
        loginTimeout: 300
        connectionTimeout: 300
        commandTimeout: 300
        interruptProcessingMode: 2

