spring:
  application:
    name: atomikos-test
  datasource:
    platform: db2
    #initialization-mode: always #Uncomment the first time to initialize database
    initialization-mode: never
  jpa:
    properties:
#      javax.persistence.schema-generation.scripts.action: create
#      javax.persistence.schema-generation.create-source: metadata
#      javax.persistence.schema-generation.scripts.create-target: src/main/resources/schema-db2.sql
      hibernate:
#        default_schema: OTHERSCHEMA # With this option, Hibernate set always schema in queries, but we don't want this.
        hbm2ddl:
          auto: none
        dialect: org.hibernate.dialect.DB2Dialect
        connection:
          autocommit: false
datasource:
    ds1:
      max-pool-size: 5
      min-pool-size: 5
      xa-data-source-class-name: com.ibm.db2.jcc.DB2XADataSource
      use-driver-based-connection-validation: true
      local-transaction-mode: true
      #init-connection-sql: set schema OTHERSCHEMA
      xa-properties:
        serverName: localhost
        portNumber: 50000
        databaseName: testdb
        currentSchema: OTHERSCHEMA
        user: db2inst1
        password: db2inst1-pwd
        clientProgramName: ${metadata.jirakey}-${metadata.slot}
        driverType: 4
        loginTimeout: 300
        connectionTimeout: 300
        commandTimeout: 300
        interruptProcessingMode: 2

