spring:
  application:
    name: atomikos-test
  datasource:
    platform: h2
  jta:
    enabled: true
    transaction-manager-id: ${spring.application.name}-tm
    atomikos:
      properties:
        checkpoint-interval: 500
datasource:
    ds1:
      max-pool-size: 5
      min-pool-size: 5
      xa-data-source-class-name: org.h2.jdbcx.JdbcDataSource
      use-driver-based-connection-validation: true
      xa-properties:
        user: test
        password: ENC(AYt9rKfJEWtpNxpTZumq9A==)
        URL: jdbc:h2:mem:db1;MODE=Oracle;IGNORECASE=TRUE;DB_CLOSE_ON_EXIT=TRUE;
    ds2:
      max-pool-size: 5
      min-pool-size: 5
      xa-data-source-class-name: org.h2.jdbcx.JdbcDataSource
      use-driver-based-connection-validation: true
      xa-properties:
        user: test
        password: ENC(AYt9rKfJEWtpNxpTZumq9A==)
        URL: jdbc:h2:mem:db2;MODE=Oracle;IGNORECASE=TRUE;DB_CLOSE_ON_EXIT=TRUE;
